# Generated by Django 3.0.5 on 2020-06-06 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskApp', '0003_auto_20200604_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='user',
        ),
        migrations.AddField(
            model_name='types',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
