# Generated by Django 3.0.5 on 2020-06-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0004_auto_20200606_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
