# Generated by Django 3.0.5 on 2020-06-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0006_auto_20200606_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
